# Generated by Django 5.1.1 on 2024-09-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commet',
            new_name='comment',
        ),
    ]
